version: '2'
services:
  fwt:
    container_name: fwt
    build:
      context: ./
      dockerfile: .docker/angular/Dockerfile
    volumes:
      - ./:/var/www/app
    ports:
      - 4200:4200
      - 4201:4201
