version: '2'
services:
  devattic:
    container_name: devattic
    build:
      context: ./
      dockerfile: .docker/angular/Dockerfile
    volumes:
      - ./:/var/www/app
    ports:
      - 4200:4200
