version: "3"
services:
    container:
      container_name: angular
      environment:
        NPM_FORCE_REBUILD: "false"
        NPM_DEV: "false"
      build:
        context: ./.docker
        dockerfile: Dockerfile
      volumes:
        - '.:/var/www/app'
        - /var/www/app/node_modules/
      ports:
        - "4200:4200"